# Generated by Django 5.1.3 on 2024-11-26 17:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserPlatformAction',
            new_name='PlatformServiceLog',
        ),
        migrations.AlterModelOptions(
            name='platformservicelog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Platform Service Log', 'verbose_name_plural': 'Platform Service Logs'},
        ),
    ]
