# Generated by Django 5.1.3 on 2024-11-25 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0003_userplatformaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='duration',
        ),
        migrations.AddField(
            model_name='track',
            name='duration_ms',
            field=models.PositiveIntegerField(blank=True, help_text='The duration of the track in milliseconds.', null=True),
        ),
        migrations.AlterField(
            model_name='trackplatforminfo',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_infos', to='platforms.track'),
        ),
    ]
