# Generated by Django 5.1.3 on 2024-11-26 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('album', models.CharField(blank=True, max_length=255, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, help_text='The duration of the track in milliseconds.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrackPlatformInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('youtube', 'youtube'), ('spotify', 'spotify')], max_length=255)),
                ('platform_id', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, help_text='The URL of the track on the platform.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_infos', to='main_app.track')),
            ],
            options={
                'verbose_name': 'Track Platform Info',
                'verbose_name_plural': 'Track Platform Infos',
                'ordering': ['platform'],
                'unique_together': {('track', 'platform')},
            },
        ),
        migrations.CreateModel(
            name='UserTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_platform', models.CharField(choices=[('youtube', 'youtube'), ('spotify', 'spotify')], max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.track')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Track',
                'verbose_name_plural': 'User Tracks',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'track', 'from_platform')},
            },
        ),
    ]
